CREATE TABLE BOOK
(
    ID               UUID           NOT NULL,
    TITLE            VARCHAR(255)   NOT NULL,
    AUTHOR           VARCHAR(255)   NOT NULL,
    PUBLICATION_YEAR INTEGER        NOT NULL,
    PRICE_AMOUNT     NUMERIC(19, 2) NOT NULL,
    PRICE_CURRENCY   VARCHAR(255)   NOT NULL,
    ISBN             VARCHAR(255)   NOT NULL,
    CONSTRAINT PK_BOOK PRIMARY KEY (ID),
    CONSTRAINT UK_BOOK_ISBN UNIQUE (ISBN)
);

CREATE INDEX IDX_BOOK_TITLE ON BOOK (TITLE);
