name: Main Deployment pipeline
on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
